apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: ftps-ip
  creationTimestamp: null
  labels:
    app: ftps
  name: ftps
spec:
  ports:
  - name: ftps-20
    port: 20
    protocol: TCP
    targetPort: 20
  - name: ftps-21
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps-30000
    port: 30000
    protocol: TCP
    targetPort: 30000
  selector:
    app: ftps
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps
        imagePullPolicy: Never
        name: ftps
        resources: {}
status: {}
