apiVersion: v1
kind: Secret
metadata:
  name: ftps-secret
type: Opaque
stringData:
  FTPS_USERNAME: user
  FTPS_PASSWORD: pass
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: IPHERE
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: cmd-ctrl-port
    port: 20
  - name: ftps-port
    port: 21
  - name: pasv-port
    port: 30000
---
# ---------- Deployment ---------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps
        name: ftps
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: ftps-secret
        resources: {}
status: {}
